require:
  - rubocop-rspec

AllCops:
  NewCops: enable
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
